### ISSUE TITLE
windows 10/64   fail with Unknown error: not yet supported on this OS

### ISSUE THREAD

**Issue by lilili87222** [fkie-cad/friTap#36]
fritap -v -p log.pcap -k keys.log --enable_spawn_gating -d 11072

Start logging
Press Ctrl+C to stop logging

[*] capturing only plaintext data
Exception type : NotSupportedError
Exception message : not yet supported on this OS
Stack trace : ['File : D:\\Program Files\\Python312\\Lib\\site-packages\\friTap\\friTap.py , Line : 120, Func.Name : main, Message : ssl_log.start_fritap_session()', 'File : D:\\Program Files\\Python312\\Lib\\site-packages\\friTap\\ssl_logger.py , Line : 439, Func.Name : start_fritap_session, Message : self.device.enable_spawn_gating()', 'File : D:\\Program Files\\Python312\\Lib\\site-packages\\frida\\core.py , Line : 86, Func.Name : wrapper, Message : return f(*args, **kwargs)', 'File : D:\\Program Files\\Python312\\Lib\\site-packages\\frida\\core.py , Line : 977, Func.Name : enable_spawn_gating, Message : self._impl.enable_spawn_gating()']

[-] Unknown error: not yet supported on this OS

Thx for using friTap
Have a great day

**Comment by monkeywave** [comment]
Hi,  

thank you for reaching out. I’d like to clarify that this is not an issue with friTap. The **spawn_gating** feature is provided directly through **Frida**, and its availability depends on Frida's support for the specific operating system in use.  

If Frida does not support **spawn_gating** on the given OS, you will encounter the message:  
> _"not yet supported on this OS"_  

For reference, you can see the relevant implementation in Frida’s source code for the windows operating system here:  
[Frida Source Code Reference](https://github.com/frida/frida-core/blob/c1472f9cb8404f7a5c86726e78aa24319ece218f/src/windows/windows-host-session.vala#L209)  

Since this limitation is rooted in Frida itself and not in friTap, I recommend opening an issue directly with the [Frida project](https://github.com/frida/frida) if you'd like to request support for your operating system. 

As this matter falls outside the scope of friTap, I will go ahead and close this issue. Please feel free to reach out if you have any other questions related to friTap.  


All the best

Daniel
