### ISSUE TITLE
Overwrites existing Frida install

### ISSUE THREAD

**Issue by brian-leidos** [fkie-cad/friTap#9]
With Frida 16.0.11 already installed, running `pip3 install fritap` results in Frida 15.x installing over my existing Frida, causing breakage to my other stuff.

**Comment by monkeywave** [comment]
Hi,

thx for reporting your issue. We tried to reproduce your issue in a fresh venv and can't reproduce it:

`
(pwn_venv) --- ~ » python3 -m pip install frida
Collecting frida
Downloading frida-16.0.19-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl (18.5 MB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 22.1 MB/s eta 0:00:00
Installing collected packages: frida
Successfully installed frida-16.0.19

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
(pwn_venv) --- ~ » python3 -m pip install fritap
Collecting fritap
Downloading friTap-1.0.9.6-py3-none-any.whl (5.3 MB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 20.7 MB/s eta 0:00:00
Requirement already satisfied: frida>=15.0.0 in ./pwn_venv/lib64/python3.11/site-packages (from fritap) (16.0.19)
Collecting frida-tools>=10.0.0
Downloading frida-tools-12.1.2.tar.gz (177 kB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 12.9 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting hexdump
Downloading hexdump-3.3.zip (12 kB)
Preparing metadata (setup.py) ... done
Collecting scapy
Downloading scapy-2.5.0.tar.gz (1.3 MB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 20.8 MB/s eta 0:00:00
Preparing metadata (setup.py) ... done
Collecting watchdog
Downloading watchdog-3.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 25.1 MB/s eta 0:00:00
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in ./pwn_venv/lib/python3.11/site-packages (from frida-tools>=10.0.0->fritap) (0.4.6)
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in ./pwn_venv/lib/python3.11/site-packages (from frida-tools>=10.0.0->fritap) (3.0.38)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in ./pwn_venv/lib/python3.11/site-packages (from frida-tools>=10.0.0->fritap) (2.13.0)
Requirement already satisfied: wcwidth in ./pwn_venv/lib/python3.11/site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools>=10.0.0->fritap) (0.2.6)
Using legacy 'setup.py install' for hexdump, since package 'wheel' is not installed.
Using legacy 'setup.py install' for scapy, since package 'wheel' is not installed.
Building wheels for collected packages: frida-tools
Building wheel for frida-tools (pyproject.toml) ... done
Created wheel for frida-tools: filename=frida_tools-12.1.2-py3-none-any.whl size=187165 sha256=5b9b2b5b5fda8681a98aca76f1aa1dfc7302a7e85135b174d78245583fcb0e4c
Stored in directory: /home/mc/.cache/pip/wheels/0a/91/0e/fa3771890712c02897fbdd86ecdf7b3b9f76eb2eae550de923
Successfully built frida-tools
Installing collected packages: hexdump, watchdog, scapy, frida-tools, fritap
Running setup.py install for hexdump ... done
Running setup.py install for scapy ... done
Successfully installed frida-tools-12.1.2 fritap-1.0.9.6 hexdump-3.3 scapy-2.5.0 watchdog-3.0.0

[notice] A new release of pip available: 22.2.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
(pwn_venv) --- ~ » frida --version
16.0.19
`

How does your environment looks like?
